apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRENSRHpNdTBiZk13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1EUXhOakUyTWpSYUZ3MHpOakEwTURFeE5qSXhNalJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURXYVFuZkRDSjdpc3dlWEdJMTBvc2VZSkl6OWJYbFJFb1dNUFZkUmdhZThGOVdDdWVYNDNZOG9tbkYKeVVXQTNOUWRoOGhDd2NVOUxmN1pYalVUZi9GWDdEOVIwdytCdktseXhxRGVJYkVHWitYU0lzVVdGTG1rbWRYTApURFhNR1dQM3I1OVZ6S1FMcjNZcVNuNXloWm5IZzlpY2FVM2IwWmp3UXVNM1pFc1VBYXZ5a1dRMTgwc2RiTi9ZCkllSW9EQm9Rc3loTm1ZL3FPanJUb0JjamdtWTh0eExWVm1OZE1RN0VMTE0rdjN4cVlsVVEwNC9nT1NNSmJDRi8KNmprcldpZlRib2ljOXVtc3ZscXI0cVFmTml0VEkyR0xmMXZoTmFNOHloeUhZNzJQVXFCbmtpVTdoRjhSb2xpZworTXhZV2ZyZ0VML1NycUNzZlhIaWdRRWF3eVROQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTcGpGa3B4U010aWhMVGZNNC9RbDRtTzQ3aWp6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnJhbjlVZTgxQQppMFJ1a1JSMm9kaWdVS0s5SWpXTUo1NDdqU3ByTmVGZVZ4d1k5bzdwY1YvKy9NdTRqT0I5MExjajBxcXBZdThWCkJJbkdFaUtrTWpOM3RoMVRVZ3MralROKzdIalBXeVR3dlNJREh0ZjBHV01JRzFOUGhPZ1hzTVh1Z0N4a0V4NE4KdWJKVlR2Wk1hbTR0a0JqMmRIbDY1WnZvNnlscE9Xd1o1Ri9tcmFiODVWSllHa2VzcVNNQUpZczMwOGQ2WlJhQwp1ZjB1OEdDbHViUXdiYS9IVHVCY0swbzRPZzlrNnFCVzNxNEc1aEp1SmtEQVRwTXhiYWtlRzZzR3paQUZMOFg2CjNBNDkyR3JhYVZYOTNZRlAya0lrZ2hWNG9wNXlUempJWHVkVGptOGpuOTYxYndtOXREWTU0UnRaVFRJcEhNcVUKdlgyUHVHRnRoWHR3Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://BFBE8A6E13F8186F1B1B6DB7D085D396.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:728635436537:cluster/eks-cluster-test
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:728635436537:cluster/eks-cluster-test
    user: arn:aws:eks:us-east-1:728635436537:cluster/eks-cluster-test
  name: arn:aws:eks:us-east-1:728635436537:cluster/eks-cluster-test
current-context: arn:aws:eks:us-east-1:728635436537:cluster/eks-cluster-test
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:728635436537:cluster/eks-cluster-test
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - eks-cluster-test
      - --output
      - json
      command: aws
