apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers: 
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alername 
        value: KubernetesPodCrashLooping
      repeatInterval: 10m
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'sharrodaws@gmail.com'
      from: 'sharrodaws@gmail.com'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'sharrodaws@gmail.com'
      authIdentity: 'sharrodaws@gmail.com'
      authPassword:
        name: gmail-auth
        key: password
