---
- name: Install Docker
  hosts: aws_ec2
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        update_cache: yes
        state: present
    - name: Start docker daemon
      systemd:
        name: docker
        state: started

- name: Create new linux user
  hosts: aws_ec2
  become: yes
  roles:
    - create_user 

    
- name: Install Docker-compose
  hosts: aws_ec2
  become: yes
  become_user: sharrod
  tasks:
    - name: Create docker-compose directory
      file:
        path: ~/.docker/cli-plugins
        state: directory
    - name: Get architecture of remote machine
      shell: uname -m
      register: remote_arch
    - name: Install docker-compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-{{ remote_arch.stdout }}"
        dest: ~/.docker/cli-plugins/docker-compose
        mode: +x

- name: Add ec2-user to docker group
  hosts: aws_ec2
  become: yes
  tasks: 
    - name: Add ec2-user to docker group
      user: 
        name: sharrod
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection


- name: Start docker containers
  hosts: aws_ec2
  become: yes
  become_user: sharrod
  vars_files:
    - project-vars.yaml
  roles:
    - start_containers