#!/usr/bin.env groovy

pipeline {   
    agent any
    stages {
        stage("test") {
            steps {
                script {
                    echo "Testing the application..."

                }
            }
        }
        stage("build") {
            steps {
                script {
                    echo "Building the application..."
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    echo 'deploying docekr image to EC2...'
                    def dockerComposeCmd = "docker-compose -f docker-compose.yaml up --detach"
                    sshagent(['ec2-server-key']) {
                        sh "scp docker-compose.yaml ec2-user@100.53.55.144:/home/ec2-user"
                        sh "ssh -o StrictHostKeyChecking=no ec2-user@100.53.55.144 ${dockerComposeCmd}"

                    }
                    echo "Deploying the application..."
                    
                }
            }
        }               
    }
} 
