
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJUHl2ZjlvS29OQmt3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1ETXlNRFF5TVRaYUZ3MHpOakF6TXpFeU1EUTNNVFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMwQzlGTzdoUTF4RFlkMUVRZHZrdWlKRm5rMG04RVEwWTNTOHh2QkdyaHpWdm4rZEc3a2JmeWJVS0wKSFBnV2NlN2Rnem5BekhuREFRQjJLbktpcm5PMXlNTkZaNFl3YmREUmhTL3lSOW9sSnAvc3J0ZlNROXJWNFdpUwpiU2djQTYyMTdWMGxuT3RLV2Z0Q09GM09sSTFwUEgrZ2txd0o4cWZ3NGpDcHZDeitIQWdYUjBGTmdpSHVuUXd6Cld5bWo2aitsc2ZlbzhqM3NrSnFCb2M1aW1PNVV5N3hHdytwLy9vdnRqbGt0MkNsS1FPNXFiYmFMNlJSNk5HMWkKeW1Bak9MNWFmYXZHaCsranlyWGYyVmV5OE5jTGErZFc5RnRzMWZPUWFjMnh6U3k5NkZaWWZ2K3dyeHJBVWZBeQpaUFVJUjZyNkk0WEE0UGhSVVpKU3pRY2RZdThEQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSdGdtZmxvckJTVGRUeUY4YUd0dzEyQTVSREJ6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVNpT1VtbUN3Lwo0VTEyMUNoTVJtWE5qQ3huZXQ3Ulp5cnhtNWZLN2ZzeTQyN0lCTTVsVC9DVzUxMmJiVEtlcW01VVVIYkk0dHlKCmlnQTV2MjVtSmhiWFVoRjZ4WXYxbDMvQm04VXNzY21IM1B4WGI0OFBqZk42UEFPMC9mRDd3NDViVUlodk5RK20KY3JoWVpTbjBraU9qc1BxRnBZMC8wUTFuS3pxZDR1Y2RPWHU5UlVLSEFVSlU3T2ExUzZTUTRrVkQ0cTFuMWwyVQpiVXdpdXkyZ2Vrc1ozUHlWMDVwTnZYSHBkOVcxdC9tcFV0dnpFVEYwcndZZ0YwUXlkc2dCVXBBWnkwdzc4QUJnCmszbGZHMEo3Z0dua3NyekN0MWU2YkNTeXhTNitDZTI1VnJaK2YvWkJjdVpIWmEyOEU4VUIrNFJTQzF2ZXh5RTMKUGJjVmdncnJTL0ZYCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0c0ab74f-b180-4cc7-b163-895b2b904d94.us-southeast-2-gw.linodelke.net:443
  name: lke587532

users:
- name: lke587532-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IkFSbWlHRlRyR2tPcjRQSk5tQzhtLXFYR3JiVFVPcGJ4enJxWlJWVWdSTmcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tdDc3MjciLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYmU1MTFjYjgtYzFkMi00NzRhLWJiMWQtZDFhMTJmY2YxNTJiIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.hxuXaZBhr-7RHtjrXrWVPA4IgulLeK797EgS8Sm3xCIYTuFL3KHLlipB_cHlT-fRuWgBqzE3DqNg16At9Vj2inuRa5eqjXk9jXVuafNqUrpdPi-b_7aNzW6WJJ_9IJrLxdKc3a2148VZg0K6yd4XhCSeXyFiLBM93ZbmrzwGuvwe8X5lnUuw5juZb7b6o-IdZvI0ixtw-WQc_h__p0RKk62qh3XWy-7jA6qNR7zhosVKnoqjsfkTqksV0U9giA0dYSZpSO3iCOMO7vjo2YyUljHgFPdss3v9cwTbQrPLbG7Zl31jkLqezHfSxyMrNZigXw3bMqUbGzWFigySGfJH8w

contexts:
- context:
    cluster: lke587532
    namespace: default
    user: lke587532-admin
  name: lke587532-ctx

current-context: lke587532-ctx
