apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSXpyQ1BtdFhmRGN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1EVXlNakE1TlRSYUZ3MHpOakEwTURJeU1qRTBOVFJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN2UHhKOWswbHZsNm5BR3g2MDVQMndiVFNnWURpZDB5eGFMVTZQL3BYZGtLbVd1N3MwRVg1UVo3WUQKRjFpRTNlaWFGdVZmZ293dGdCeW9PenVTR3dPRDhUVXoyMTlWN1p3NndZZmVZS3h4NFBmU3dEb3loYXRzdEdERAo5L2wwV1hZNnMvT2RWclc3SmxSZmUvdXlXbDhZZEd4blczdmhlWVNobUdUYzVOSDZGc2dQK1A1c2RDRzRHL0hICnplOWlSWG16WVVOV2xDUi9RaG5PNXVDcUROV1RPR1hreEZLMnV3YlBxU2J1RFI1V0xBRHNFN3lJY2tYQkE0VkkKRzRtdVpuQm14dFpqcm9qVXU5RWNiUXF3TjVOU3NMbXZvVDN4VkVZOE9pVy9ucmRVS1pURzk2U0xhV2R4MHo4UQp1M2JrODhiV1JMOUZXWUZrRG1qalFySjZGR2ZiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSR2tudlEreE5EdUZCL1hlVW83VzU2b3FNU3VEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkh5Q01GeHNyUgp6aUJ5VU1XdjNHUlkzbjZDc28xWVEwMHdvZnlwT0ZsSUsvNC82d25nL3F0aUE5SE13ZzNxQlNzSVJmZFlyODlICjcxSG1OZXZncSs1SmUrUk9MaWN2WlQ3UmN5Y3lQZ3NVaXJyWDRxQW9wOUZnTjlpSnkrYU5ya0FDcnhCeWx1QjYKTVJYQnJzMkRJYVNiS2xmVUF2UmFWNVlhMldpb2FMUytWaVVBbXVDaDYwVTV0RFJ2a01UN1BUSFN0ZktCVTRndwp2ZFRPM0F2bG9ycGFBeGZvVXd3eEpzZXNtR3FyS3lTM0JmcVRJMDhqaVNxTnZUVXlTNVF4SVdOanI5N1prWTBKCnVjYjBwYzlkaEgrNjdZT0R1OVFISTlDMUxlT3RwSGJWVElTbGticVZpUis3UnZhTlMxRWJmQmpwVEF1dkxJS1YKYUlTa0tIdVlyaFNHCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0
    server: https://85038B743F0270FD519E9D1E2804C661.yl4.us-east-1.eks.amazonaws.com 
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: /usr/local/bin/aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "demo-cluster"
