
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJREljWUxwcjJVa0l3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1ETXhOekF4TlRkYUZ3MHpOakF6TXpFeE56QTJOVGRhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURjczYvanM1L2R5TEdYVVdJTUM3N2pMSk1BY0lOV2paSEQxOWdyQUVJcmI4bXFkY0dnMVFpb2tBVTUKZkVlMk8zdy9NSkZkcytLVXZGRjZaUTczTXptY0w0b240OGpVNE5rRzRmckx3RXgvbXZjN1BwRkJGWWwvaER6MgpEdmFRWnpsQWowM0orWnNRSTMyYXFKZU5NeEtvcWE0Tnd3OXFzc25BUjVROHZZOFlnbUQzTlE5S1ovOFJWejg1CmRnOFhHYlRQV0IzeHBWSkZoQndZRVpJalYwKzBldEVmKzhjNzBkb21LMWkyUktmSWhhRUdwa21zZjlsZlZLQjQKUXRCSzhaSG9DWDhYMlVmZFh1RDV3R3RGU0x4citHaHV5TDlVRjBnOGM5REt6SGIxQWVOaFowZ051SjBjREZkdwpkdWgvS0JzSHJJZ1B3UGVWY0h0YTNjNHcra3hQQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRR1hWMW9Zbi9LczYrUlIxRXF5cXh2dXlrTTZqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQU1ONzhaazBtNwo4MkdzNFYrY0k1RXZ3N2NFSDBrS0pzNlRGZnMrNGZEZXl0TWNSNTZOdG1wRFFCNGZsWWtZdDl2UlJ2WkpjYW0xCkxKQlRvR0hwVzRSR1pFQzJROXFadU4rVzEvT3Ztb2xUYUhhajJEVXBGYUZJU3lJb3RyNHQyQzZoSi9XNm9vRlcKRWY1SytwSVFuVThrNWJzZ1E5WkNtRGJFMzFienZ5akxlemh3TnBtT05rK0I4N1d4SEtPOXdWcHptVm9ySDJMQgpkbmdUREJDOTV0RVRZY1BrdFdYVGRNaUE5UjVBYUc2YU1ISml6ZFFWYTBueG1vdU11RTBlY09jUjR1U05nVytVCkF0WjdSSWJEVkhpWm1peW53NEh6Zm5WNVBOYTFEOFdsdW9rYzVVTnJZNFQwTXZVRnBDWms0dGJNb0JYR2wyVTAKNGdNdmhjc3ZsbnpUCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9a9f665f-606b-4a45-bc17-06dfcf3a1ebd.us-southeast-1-gw.linodelke.net:443
  name: lke587503

users:
- name: lke587503-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IktPX2JtcDVLTHduRWhuemNJUm9Gd1EyU2UzSlVnY1RSV2pyRGNuS2RxVFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tNWQ2cnYiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiMDViZWNmYWYtNjQ3My00MTU1LWFlN2EtYmE0YTk4ZGNjMmQxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.xXdBNd6NwpcKfTiD46Y5J0jsESE3pvri4xAwPGhzcpjalK1BXQ2CHzKRR4QAxWU2eczNOj8Go7CeUB8GpyGAOR1bbCioKHR_wezp27Wt7bmt9YDjvN5LPnIUFH9uIT3lIG8yKG4U3dILbkU8mAXpHOqPx4ySgqOwLmNK8Ddi2y0EarngHhbdv46vHpbx_hAs7aJ8k1Mbtk7XfaNx1-hTuWzIeABpo6VU0mWA9vEtd434iWsFMod8RlCplWoAJGSneEUDPNRPYpIb7bPrZ_aBsaKeNs4-cNDOHb5Kq7pWCyVOa_wYv50Xp8DbO-EJ0z8n5peB83h3E9G1tuD6_ng7yw

contexts:
- context:
    cluster: lke587503
    namespace: default
    user: lke587503-admin
  name: lke587503-ctx

current-context: lke587503-ctx
