#!/usr/bin/env groovy
pipeline {
    agent any
    tools {
        maven 'maven-3.9'
    }
    environment {
        DOCKER_REPO_SERVER = '728635436537.dkr.ecr.us-east-1.amazonaws.com'
        DOCKER_REPO = "${DOCKER_REPO_SERVER}/java-maven-app"
    }
    stages {
        stage('increment version') {
            steps {
                script {
                    echo 'incrementing app version...'
                    sh 'mvn -f TWN-EKS/java-maven-app/pom.xml build-helper:parse-version versions:set \
                        -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                        versions:commit'
                    def matcher = readFile('TWN-EKS/java-maven-app/pom.xml') =~ '<version>(.+)</version>'
                    def version = matcher[0][1]
                    env.IMAGE_NAME = "$version-$BUILD_NUMBER"
                }
            }
        }
        stage('build app') {
            steps {
                script {
                    echo 'building the application...'
                    sh 'mvn -f TWN-EKS/java-maven-app/pom.xml clean package'
                }
            }
        }
        stage('build image') {
            steps {
                script {
                    echo 'building the docker image...'
                    withCredentials([usernamePassword(credentialsId: 'ecr-credentials', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        sh "docker build -t ${DOCKER_REPO}:${IMAGE_NAME} -f TWN-EKS/java-maven-app/Dockerfile TWN-EKS/java-maven-app"
                        sh "echo \$PASS | docker login -u \$USER --password-stdin ${DOCKER_REPO_SERVER}"
                        sh "docker push ${DOCKER_REPO}:${IMAGE_NAME}"
                    }
                }
            }
        }
        stage('deploy') {
            environment {
                AWS_ACCESS_KEY_ID = credentials('TWN-EKS-Jenkins-AWS-access-key-id')
                AWS_SECRET_ACCESS_KEY = credentials('TWN-EKS-Jenkins-AWS-Secret-access-id')
                APP_NAME = 'java-maven-app'
            }
            steps {
                script {
                    echo 'deploying docker image...'
                    sh 'envsubst < TWN-EKS/java-maven-app/kubernetes/deployment.yaml | kubectl apply -f -'
                    sh 'envsubst < TWN-EKS/java-maven-app/kubernetes/service.yaml | kubectl apply -f -'
                }
            }
        }
        stage('commit version update') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'github-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                        sh 'git config --global user.email "jenkins@example.com"'
                        sh 'git config --global user.name "jenkins"'
                        sh "git remote set-url origin https://${USER}:${PASS}@github.com/sharrods/TWN.git"
                        sh 'git checkout jenkins-jobs'
                        sh 'git pull origin jenkins-jobs'
                        sh 'git add .'
                        sh 'git commit -m "ci: version bump"'
                        sh 'git push origin jenkins-jobs'
                    }
                }
            }
        }
    }
}
