pipeline {   
    agent any
    stages {
        stage("Build") {
            steps {
                script {
                    echo "Building Application..."
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    echo "Buildnig the image..."
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    echo 'deploying docker image...'
                    withKubeConfig([credentialsId: 'lke-creds', serverUrl: 'https://f8cdca95-5ea5-426d-9ef2-58783fc333ec.us-southeast-2-gw.linodelke.net']) {
                        sh 'kubectl create deployment nginx-deployment --image=nginx'
                    }
                }
            }
        }               
    }
} 
