---
- name: Install node and npm
  hosts: ec2-3-91-209-227.compute-1.amazonaws.com
  become: yes
  tasks:
    - name: Update Cache
      yum: update_cache=yes 
    - name: Install nodejs and npm
      yum: 
        name:
          - nodejs
          - npm
        state: present

- name: Deploy nodejs app
  hosts: ec2-3-91-209-227.compute-1.amazonaws.com
  tasks:
    - name: Copy/Unpack nodejs file to remote server 
      unarchive:
        src: /Users/sharrods/Documents/Techworld-with-nana/TWN-Ansible/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /home/ec2-user/
    - name: Install dependencies
      npm:
        path: /home/ec2-user/package
    - name: Start the application
      command:
        chdir: /home/ec2-user/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status}}

      