---
- name: Install node and npm
  hosts: ec2-3-91-209-227.compute-1.amazonaws.com
  become: yes
  tasks:
    - name: Update Cache
      yum: update_cache=yes 
    - name: Install nodejs and npm
      yum: 
        name:
          - nodejs
          - npm
        state: present

- name: Create new user for node app
  hosts: ec2-3-91-209-227.compute-1.amazonaws.com
  become: True
  tasks:
    - name: Create linux user
      user:
        name: sharrod
        comment: Create sharrod
        group: wheel


- name: Deploy nodejs app
  hosts: ec2-3-91-209-227.compute-1.amazonaws.com
  become: True
  become_user: sharrod
  tasks:
    - name: Copy/Unpack nodejs file to remote server 
      unarchive:
        src: /Users/sharrods/Documents/Techworld-with-nana/TWN-Ansible/nodejs-app/nodejs-app-1.0.0.tgz
        dest: /home/sharrod/
      register: user_creation_result
    - debug: msg={{user_creation_result}}
    - name: Install dependencies
      npm:
        path: /home/sharrod/package
    - name: Start the application
      command:
        chdir: /home/sharrod/package/app
        cmd: node server
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}

      