#!/usr/bin/env groovy

pipeline {   
  agent any
  tools {
    maven 'maven-3.9'
  }
  environment {
    IMAGE_NAME = 'sharrods/demo-app:java-maven-2.0'
  }
  stages {
    stage("build app") {
      steps {
        script {
          echo 'building application jar...'
          sh 'mvn -f TWN-Terraform/java-maven-app/pom.xml clean package'
        }
      }
    }
    stage("build image") {
      steps {
        script {
          echo 'building docker image...'
          withCredentials([usernamePassword(credentialsId: 'docker-hub-repo', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
            sh "docker build -t ${IMAGE_NAME} -f TWN-Terraform/java-maven-app/Dockerfile TWN-Terraform/java-maven-app"
            sh 'echo $PASS | docker login -u $USER --password-stdin'
            sh "docker push ${IMAGE_NAME}"
          }
        }
      }
    }
    stage("provision server") {
      environment {
        AWS_ACCESS_KEY_ID     = credentials('jenkins_aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('jenkins_aws_secret')
        TF_VAR_env_prefix     = 'test'
      }
      steps {
        script {
          dir('TWN-Terraform/java-maven-app/Terraform') {
            sh "terraform init -migrate-state -force-copy -input=false"
            sh "terraform destroy --auto-approve"
            EC2_PUBLIC_IP = sh(
              script: "terraform output ec2_public_ip",
              returnStdout: true
            ).trim()
          }
        }
      }
    }
    stage("deploy") {
      environment {
        DOCKER_CREDS = credentials('docker-hub-repo')
      }
      steps {
        script {
          echo "waiting for EC2 server to initialize"
          sleep(time: 90, unit: "SECONDS")
          echo 'deploying docker image to EC2...'
          echo "${EC2_PUBLIC_IP}"

          def shellCmd = "bash ./server-cmds.sh ${IMAGE_NAME} ${DOCKER_CREDS_USR} ${DOCKER_CREDS_PSW}"
          def ec2Instance = "ec2-user@${EC2_PUBLIC_IP}"

          sshagent(['server-ssh-key']) {
            sh "scp -o StrictHostKeyChecking=no TWN-Terraform/java-maven-app/server-cmds.sh ${ec2Instance}:/home/ec2-user"
            sh "scp -o StrictHostKeyChecking=no TWN-Terraform/java-maven-app/docker-compose.yaml ${ec2Instance}:/home/ec2-user"
            sh "ssh -o StrictHostKeyChecking=no ${ec2Instance} ${shellCmd}"
          }
        }
      }
    }               
  }
}